language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

install:
  - travis_retry composer self-update
  - composer config -g github-oauth.github.com $GITHUB_TOKEN
  - composer install

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)
